(defun wrk-color-fancy nil
  "toggles between color sets"
  (interactive)
;;   (set-background-color "DarkSlateGrey")
;;   (set-foreground-color "Wheat")
;;   (set-cursor-color "Orchid")
;;   (setq paren-match-face (quote paren-face-match-fancy))
  (my-color-theme-fancy)
  )

(defun wrk-color-normal nil
  "toggles between color sets"
  (interactive)
;;   (set-background-color "White")
;;   (set-foreground-color "Black")
;;   (set-cursor-color "Black")
;;   (setq paren-match-face (quote paren-face-match-normal))
  (my-color-theme-normal)
  )

(and (or (= emacs-major-version 23) 
	 (= emacs-major-version 24)) 
     (include 'color-theme))
;;(message "color-theme not present")

    ;; (color-theme-initialize)
    ;;(color-theme-classic)
    ;;(setq paren-match-face (quote paren-face-match-fancy))
    
(defun my-color-theme-fancy ()
  "Color theme by Karsten Lang, created 2009-03-11."
  (interactive)
  (color-theme-install
   '(my-color-theme-fancy
     ((background-color . "DarkSlateGrey")
      (background-mode . dark)
      (border-color . "black")
      (cursor-color . "Orchid")
      (foreground-color . "Wheat")
      (mouse-color . "black"))
     ((list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . match)
      (paren-match-face . paren-face-match-fancy)
      (paren-mismatch-face . paren-face-mismatch)
      (paren-no-match-face . paren-face-no-match)
      (php-default-face . default)
      (rmail-highlight-face . rmail-highlight)
      (tags-tag-face . default)
      (view-highlight-face . highlight)
      (widget-mouse-face . highlight))
     (default ((t (:background "DarkSlateGrey" :foreground "Wheat"))))
     (bold ((t (:bold (bold extra-bold ultra-bold)))))
     (bold-italic ((t (:italic (italic oblique) :bold (bold extra-bold ultra-bold)))))
     (border ((t (:background "black"))))
     (buffer-menu-buffer ((t (:bold (bold extra-bold ultra-bold)))))
     (button ((t (:underline t))))
     (comint-highlight-input ((t (:bold (bold extra-bold ultra-bold)))))
     (comint-highlight-prompt ((t (:foreground "cyan1"))))
     (completions-common-part ((t (nil))))
     (completions-first-difference ((t (nil))))
     (cursor ((t (:background "Orchid"))))
     (custom-button ((t (:background "lightgrey" :foreground "black"))))
     (custom-button-mouse ((t (:background "grey90" :foreground "black"))))
     (custom-button-pressed ((t (:background "lightgrey" :foreground "black"))))
     (custom-button-pressed-unraised ((t (:foreground "violet"))))
     (custom-button-unraised ((t (nil))))
     (custom-changed ((t (:background "blue1" :foreground "white"))))
     (custom-comment ((t (:background "dim gray"))))
     (custom-comment-tag ((t (:foreground "gray80"))))
     (custom-documentation ((t (nil))))
     (custom-face-tag ((t (:bold (bold extra-bold ultra-bold)))))
     (custom-group-tag ((t (:bold (bold extra-bold ultra-bold) :foreground "light blue"))))
     (custom-group-tag-1 ((t (:bold (bold extra-bold ultra-bold) :foreground "pink"))))
     (custom-invalid ((t (:background "red1" :foreground "yellow1"))))
     (custom-link ((t (nil))))
     (custom-modified ((t (:background "blue1" :foreground "white"))))
     (custom-rogue ((t (:background "black" :foreground "pink"))))
     (custom-saved ((t (:underline t))))
     (custom-set ((t (:background "white" :foreground "blue1"))))
     (custom-state ((t (:foreground "lime green"))))
     (custom-themed ((t (:background "blue1" :foreground "white"))))
     (custom-variable-button ((t (:underline t :bold (bold extra-bold ultra-bold)))))
     (custom-variable-tag ((t (:bold (bold extra-bold ultra-bold) :foreground "light blue"))))
     (dropdown-list-face ((t (:background "lightyellow" :foreground "black"))))
     (dropdown-list-selection-face ((t (:background "purple"))))
     (escape-glyph ((t (:foreground "cyan"))))
     (file-name-shadow ((t (nil))))
     (fixed-pitch ((t (nil))))
     (font-lock-builtin-face ((t (:foreground "LightSteelBlue"))))
     (font-lock-comment-delimiter-face ((t (:foreground "chocolate1"))))
     (font-lock-comment-face ((t (:foreground "chocolate1"))))
     (font-lock-constant-face ((t (:foreground "Aquamarine"))))
     (font-lock-doc-face ((t (nil))))
     (font-lock-function-name-face ((t (:foreground "LightSkyBlue"))))
     (font-lock-keyword-face ((t (:foreground "Cyan1"))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-preprocessor-face ((t (nil))))
     (font-lock-regexp-grouping-backslash ((t (nil))))
     (font-lock-regexp-grouping-construct ((t (nil))))
     (font-lock-string-face ((t (:foreground "LightSalmon"))))
     (font-lock-type-face ((t (:foreground "PaleGreen"))))
     (font-lock-variable-name-face ((t (:foreground "LightGoldenrod"))))
     (font-lock-warning-face ((t (:bold (bold extra-bold ultra-bold) :foreground "Pink"))))
     (fringe ((t (:background "grey10"))))
     (header-line ((t (:background "grey20" :foreground "grey90"))))
     (help-argument-name ((t (nil))))
     (highlight ((t (:background "darkolivegreen"))))
     (highlight-current-line-face ((t (:background "#335A4B"))))
     (isearch ((t (:background "palevioletred2" :foreground "brown4"))))
     (iswitchb-current-match ((t (nil))))
     (iswitchb-invalid-regexp ((t (nil))))
     (iswitchb-single-match ((t (nil))))
     (iswitchb-virtual-matches ((t (nil))))
     (italic ((t (:italic (italic oblique)))))
     (lazy-highlight ((t (:background "paleturquoise4"))))
     (link ((t (:underline t :foreground "cyan1"))))
     (link-visited ((t (:foreground "violet"))))
     (match ((t (:background "RoyalBlue3"))))
     (menu ((t (:background "grey75" :foreground "#101010" :inverse-video t))))
     (message-cited-text ((t (:foreground "red"))))
     (message-header-cc ((t (:bold (bold extra-bold ultra-bold) :foreground "green4"))))
     (message-header-name ((t (:foreground "DarkGreen"))))
     (message-header-newsgroups ((t (:italic (italic oblique) :bold (bold extra-bold ultra-bold) :foreground "blue4"))))
     (message-header-other ((t (:foreground "#b00000"))))
     (message-header-subject ((t (:bold (bold extra-bold ultra-bold) :foreground "navy blue"))))
     (message-header-to ((t (:bold (bold extra-bold ultra-bold) :foreground "MidnightBlue"))))
     (message-header-xheader ((t (:foreground "blue"))))
     (message-mml ((t (:foreground "ForestGreen"))))
     (message-separator ((t (:foreground "blue3"))))
     (minibuffer-noticeable-prompt ((t (:background "SkyBlue4"))))
     (minibuffer-prompt ((t (:foreground "cyan"))))
     (mode-line ((t (:background "grey75" :foreground "black"))))
     (mode-line-buffer-id ((t (:bold (bold extra-bold ultra-bold)))))
     (mode-line-highlight ((t (nil))))
     (mode-line-inactive ((t (:background "grey45" :foreground "grey80"))))
     (mouse ((t (:background "black"))))
     (next-error ((t (nil))))
     (nobreak-space ((t (:underline t))))
     (paren-face-match ((t (:background "turquoise"))))
     (paren-face-match-fancy ((t (:background "#335353"))))
     (paren-face-match-normal ((t (:background "azure"))))
     (paren-face-mismatch ((t (:background "purple" :foreground "white"))))
     (paren-face-no-match ((t (:background "yellow" :foreground "black"))))
     (query-replace ((t (nil))))
     (region ((t (:background "blue3"))))
     (scroll-bar ((t (:background "grey75" :foreground "#101010"))))
     (secondary-selection ((t (:background "SkyBlue4"))))
     (sh-escaped-newline ((t (nil))))
     (sh-heredoc ((t (:bold (bold extra-bold ultra-bold) :foreground "yellow1"))))
     (sh-quoted-exec ((t (:foreground "salmon"))))
     (shadow ((t (:foreground "grey70"))))
     (show-paren-match ((t (:background "steelblue3"))))
     (show-paren-mismatch ((t (:background "purple" :foreground "white"))))
     (speedbar-button-face ((t (:foreground "green3"))))
     (speedbar-directory-face ((t (:foreground "light blue"))))
     (speedbar-file-face ((t (:foreground "cyan"))))
     (speedbar-highlight-face ((t (:background "sea green"))))
     (speedbar-selected-face ((t (:underline t :foreground "red"))))
     (speedbar-separator-face ((t (:background "blue" :foreground "white"))))
     (speedbar-tag-face ((t (:foreground "yellow"))))
     (tool-bar ((t (:background "#efebe7" :foreground "#101010"))))
     (tooltip ((t (:background "lightyellow" :foreground "black"))))
     (trailing-whitespace ((t (:background "red1"))))
     (underline ((t (:underline t))))
     (variable-pitch ((t (nil))))
     (vertical-border ((t (nil))))
     (widget-button ((t (:bold (bold extra-bold ultra-bold)))))
     (widget-button-pressed ((t (:foreground "red1"))))
     (widget-documentation ((t (:foreground "lime green"))))
     (widget-field ((t (:background "dim gray"))))
     (widget-inactive ((t (nil))))
     (widget-link ((t (nil))))
     (widget-single-line-field ((t (:background "dim gray"))))
     (yas/field-highlight-face ((t (:background "DimGrey"))))
     (yas/mirror-highlight-face ((t (:background "gray22")))))))

(defun my-color-theme-normal ()
  "Color theme by Karsten Lang, created 2009-04-28."
  (interactive)
  (color-theme-install
   '(my-color-theme-normal
     ((background-color . "White")
      (background-mode . light)
      (border-color . "black")
      (cursor-color . "black")
      (foreground-color . "Black")
      (mouse-color . "black"))
     ((Man-overstrike-face . bold)
      (Man-reverse-face . highlight)
      (Man-underline-face . underline)
      (compilation-message-face . underline)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . match)
      (paren-match-face . paren-face-match-normal)
      (paren-mismatch-face . paren-face-mismatch)
      (paren-no-match-face . paren-face-no-match)
      (php-default-face . default)
      (rmail-highlight-face . rmail-highlight)
      (tags-tag-face . default)
      (view-highlight-face . highlight)
      (widget-mouse-face . highlight))
     (default ((t (:background "White" :foreground "Black"))))
     (anything-bookmarks-su-face ((t (:foreground "red"))))
     (anything-dir-heading ((t (:background "Pink" :foreground "Blue"))))
     (anything-dir-priv ((t (:background "LightGray" :foreground "DarkRed"))))
     (anything-file-name ((t (:foreground "Blue"))))
     (anything-gentoo-match-face ((t (:foreground "red"))))
     (anything-header ((t (nil))))
     (anything-isearch-match ((t (:background "Yellow"))))
     (anything-overlay-line-face ((t (:underline t :background "IndianRed4"))))
     (anything-visible-mark ((t (:background "green1"))))
     (anything-w3m-bookmarks-face ((t (:underline t :foreground "cyan1"))))
     (bold ((t (:bold (bold extra-bold ultra-bold)))))
     (bold-italic ((t (:italic (italic oblique) :bold (bold extra-bold ultra-bold)))))
     (bookmark-menu-heading ((t (nil))))
     (border ((t (:background "black"))))
     (buffer-menu-buffer ((t (:bold (bold extra-bold ultra-bold)))))
     (button ((t (:underline t))))
     (comint-highlight-input ((t (:bold (bold extra-bold ultra-bold)))))
     (comint-highlight-prompt ((t (:foreground "dark blue"))))
     (compilation-column-number ((t (nil))))
     (compilation-error ((t (nil))))
     (compilation-info ((t (:bold (bold extra-bold ultra-bold) :foreground "Green3"))))
     (compilation-line-number ((t (nil))))
     (compilation-warning ((t (:bold (bold extra-bold ultra-bold) :foreground "Orange"))))
     (completions-common-part ((t (nil))))
     (completions-first-difference ((t (nil))))
     (cursor ((t (:background "black"))))
     (custom-button ((t (:background "lightgrey" :foreground "black"))))
     (custom-button-mouse ((t (:background "grey90" :foreground "black"))))
     (custom-button-pressed ((t (:background "lightgrey" :foreground "black"))))
     (custom-button-pressed-unraised ((t (:foreground "magenta4"))))
     (custom-button-unraised ((t (nil))))
     (custom-changed ((t (:background "blue1" :foreground "white"))))
     (custom-comment ((t (:background "gray85"))))
     (custom-comment-tag ((t (:foreground "blue4"))))
     (custom-documentation ((t (nil))))
     (custom-face-tag ((t (:bold (bold extra-bold ultra-bold)))))
     (custom-group-tag ((t (:bold (bold extra-bold ultra-bold) :foreground "blue1"))))
     (custom-group-tag-1 ((t (:bold (bold extra-bold ultra-bold) :foreground "red1"))))
     (custom-invalid ((t (:background "red1" :foreground "yellow1"))))
     (custom-link ((t (nil))))
     (custom-modified ((t (:background "blue1" :foreground "white"))))
     (custom-rogue ((t (:background "black" :foreground "pink"))))
     (custom-saved ((t (:underline t))))
     (custom-set ((t (:background "white" :foreground "blue1"))))
     (custom-state ((t (:foreground "dark green"))))
     (custom-themed ((t (:background "blue1" :foreground "white"))))
     (custom-variable-button ((t (:underline t :bold (bold extra-bold ultra-bold)))))
     (custom-variable-tag ((t (:bold (bold extra-bold ultra-bold) :foreground "blue1"))))
     (dired-directory ((t (nil))))
     (dired-flagged ((t (nil))))
     (dired-header ((t (nil))))
     (dired-ignored ((t (nil))))
     (dired-mark ((t (nil))))
     (dired-marked ((t (nil))))
     (dired-symlink ((t (nil))))
     (dired-warning ((t (nil))))
     (dropdown-list-face ((t (:background "lightyellow" :foreground "black"))))
     (dropdown-list-selection-face ((t (:background "purple"))))
     (escape-glyph ((t (:foreground "brown"))))
     (ffap ((t (nil))))
     (file-name-shadow ((t (nil))))
     (fixed-pitch ((t (nil))))
     (font-lock-builtin-face ((t (:foreground "Orchid"))))
     (font-lock-comment-delimiter-face ((t (nil))))
     (font-lock-comment-face ((t (:foreground "Firebrick"))))
     (font-lock-constant-face ((t (:foreground "CadetBlue"))))
     (font-lock-doc-face ((t (nil))))
     (font-lock-function-name-face ((t (:foreground "Blue1"))))
     (font-lock-keyword-face ((t (:foreground "Purple"))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-preprocessor-face ((t (nil))))
     (font-lock-regexp-grouping-backslash ((t (nil))))
     (font-lock-regexp-grouping-construct ((t (nil))))
     (font-lock-string-face ((t (:foreground "RosyBrown"))))
     (font-lock-type-face ((t (:foreground "ForestGreen"))))
     (font-lock-variable-name-face ((t (:foreground "DarkGoldenrod"))))
     (font-lock-warning-face ((t (:bold (bold extra-bold ultra-bold) :foreground "Red1"))))
     (fringe ((t (:background "grey95"))))
     (header-line ((t (:background "grey90" :foreground "grey20"))))
     (help-argument-name ((t (nil))))
     (highlight ((t (:background "darkseagreen2"))))
     (highlight-current-line-face ((t (:background "wheat"))))
     (isearch ((t (:background "magenta3" :foreground "lightskyblue1"))))
     (iswitchb-current-match ((t (nil))))
     (iswitchb-invalid-regexp ((t (nil))))
     (iswitchb-single-match ((t (nil))))
     (iswitchb-virtual-matches ((t (nil))))
     (italic ((t (:italic (italic oblique)))))
     (lazy-highlight ((t (:background "paleturquoise"))))
     (link ((t (:underline t :foreground "blue1"))))
     (link-visited ((t (:foreground "magenta4"))))
     (match ((t (:background "yellow"))))
     (menu ((t (:background "grey75" :foreground "#101010" :inverse-video t))))
     (minibuffer-noticeable-prompt ((t (:background "gold"))))
     (minibuffer-prompt ((t (:foreground "medium blue"))))
     (mode-line ((t (:background "grey75" :foreground "black"))))
     (mode-line-buffer-id ((t (:bold (bold extra-bold ultra-bold)))))
     (mode-line-highlight ((t (nil))))
     (mode-line-inactive ((t (:background "grey90" :foreground "grey20"))))
     (mouse ((t (:background "black"))))
     (next-error ((t (nil))))
     (nobreak-space ((t (:underline t))))
     (paren-face-match ((t (:background "turquoise"))))
     (paren-face-match-fancy ((t (:background "#335353"))))
     (paren-face-match-normal ((t (:background "azure"))))
     (paren-face-mismatch ((t (:background "purple" :foreground "white"))))
     (paren-face-no-match ((t (:background "yellow" :foreground "black"))))
     (query-replace ((t (nil))))
     (region ((t (:background "lightgoldenrod2"))))
     (scroll-bar ((t (:foreground "#101010"))))
     (secondary-selection ((t (:background "yellow1"))))
     (shadow ((t (:foreground "grey50"))))
     (show-paren-match ((t (:background "turquoise"))))
     (show-paren-mismatch ((t (:background "purple" :foreground "white"))))
     (speedbar-button-face ((t (:foreground "green4"))))
     (speedbar-directory-face ((t (:foreground "blue4"))))
     (speedbar-file-face ((t (:foreground "cyan4"))))
     (speedbar-highlight-face ((t (:background "green"))))
     (speedbar-selected-face ((t (:underline t :foreground "red"))))
     (speedbar-separator-face ((t (:background "blue" :foreground "white"))))
     (speedbar-tag-face ((t (:foreground "brown"))))
     (tool-bar ((t (:background "#efebe7" :foreground "#101010"))))
     (tooltip ((t (:background "lightyellow" :foreground "black"))))
     (trailing-whitespace ((t (:background "red1"))))
     (underline ((t (:underline t))))
     (variable-pitch ((t (nil))))
     (vertical-border ((t (nil))))
     (widget-button ((t (:bold (bold extra-bold ultra-bold)))))
     (widget-button-pressed ((t (:foreground "red1"))))
     (widget-documentation ((t (:foreground "dark green"))))
     (widget-field ((t (:background "gray85"))))
     (widget-inactive ((t (nil))))
     (widget-link ((t (nil))))
     (widget-single-line-field ((t (:background "gray85"))))
     (woman-addition ((t (:foreground "orange"))))
     (woman-bold ((t (:bold (bold extra-bold ultra-bold) :foreground "blue1"))))
     (woman-italic ((t (:underline t :italic (italic oblique) :foreground "red1"))))
     (woman-symbol ((t (nil))))
     (woman-unknown ((t (:foreground "brown"))))
     (yas/field-highlight-face ((t (:background "DarkSeaGreen2"))))
     (yas/mirror-highlight-face ((t (:background "LightYellow2")))))))

(if (or (= emacs-major-version 23) (= emacs-major-version 24))
 (my-color-theme-fancy))
  
