(deftheme fancy-automatic
  "Created 2013-08-08.")

(custom-theme-set-faces
 'fancy-automatic
 '(default ((t (:family "Monaco" :foundry "apple" :width normal :height 120 :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "Wheat" :background "DarkSlateGrey" :stipple nil :inherit nil))))
 '(cursor ((t (:background "Orchid"))))
 '(fixed-pitch ((t nil)))
 '(variable-pitch ((t nil)))
 '(escape-glyph ((t (:foreground "cyan"))))
 '(minibuffer-prompt ((t (:foreground "cyan"))))
 '(highlight ((t (:background "darkolivegreen"))))
 '(region ((t (:background "blue3"))))
 '(shadow ((t (:foreground "grey70"))))
 '(secondary-selection ((t (:background "SkyBlue4"))))
 '(trailing-whitespace ((t (:background "red1"))))
 '(font-lock-builtin-face ((t (:foreground "LightSteelBlue"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "chocolate1" :inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "chocolate1"))))
 '(font-lock-constant-face ((t (:foreground "Aquamarine"))))
 '(font-lock-doc-face ((t nil)))
 '(font-lock-function-name-face ((t (:foreground "LightSkyBlue"))))
 '(font-lock-keyword-face ((t (:foreground "Cyan1"))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((t nil)))
 '(font-lock-regexp-grouping-backslash ((t nil)))
 '(font-lock-regexp-grouping-construct ((t nil)))
 '(font-lock-string-face ((t (:foreground "LightSalmon"))))
 '(font-lock-type-face ((t (:foreground "PaleGreen"))))
 '(font-lock-variable-name-face ((t (:foreground "LightGoldenrod"))))
 '(font-lock-warning-face ((t (:weight bold :foreground "Pink" :inherit (error)))))
 '(button ((t (:underline (:color foreground-color :style line) :inherit (link)))))
 '(link ((t (:foreground "cyan1" :underline (:color foreground-color :style line)))))
 '(link-visited ((t (:foreground "violet" :inherit (link)))))
 '(fringe ((t (:background "grey10"))))
 '(header-line ((t (:box nil :foreground "grey90" :background "grey20" :inherit (mode-line)))))
 '(tooltip ((t (:foreground "black" :background "lightyellow" :inherit (variable-pitch)))))
 '(mode-line ((t (:box (:line-width -1 :color nil :style released-button) :foreground "black" :background "grey75"))))
 '(mode-line-buffer-id ((t (:bold (bold extra-bold ultra-bold)))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((t nil)))
 '(mode-line-inactive ((t (:weight light :box (:line-width -1 :color "grey40" :style nil) :foreground "grey80" :background "grey45" :inherit (mode-line)))))
 '(isearch ((t (:foreground "brown4" :background "palevioletred2"))))
 '(isearch-fail ((((class color) (min-colors 88) (background light)) (:background "RosyBrown1")) (((class color) (min-colors 88) (background dark)) (:background "red4")) (((class color) (min-colors 16)) (:background "red")) (((class color) (min-colors 8)) (:background "red")) (((class color grayscale)) (:foreground "grey")) (t (:inverse-video t))))
 '(lazy-highlight ((t (:background "paleturquoise4"))))
 '(match ((t (:background "RoyalBlue3"))))
 '(next-error ((t nil)))
 '(query-replace ((t nil))))

(provide-theme 'fancy-automatic)
